Timesheet/main/default/objects/Dashboard_Profile_Config__mdt/Dashboard_Profile_Config__mdt.object-meta.xml
<CustomObject>
    <label>Dashboard Profile Config</label>
    <pluralLabel>Dashboard Profile Configs</pluralLabel>
</CustomObject>

Timesheet/main/default/objects/Dashboard_Profile_Config__mdt/fields/Column_1_Fields__c.field-meta.xml
<CustomField>
    <fullName>Column_1_Fields__c</fullName>
    <label>Column 1 Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Timesheet/main/default/objects/Dashboard_Profile_Config__mdt/fields/Column_2_Fields__c.field-meta.xml
<CustomField>
    <fullName>Column_2_Fields__c</fullName>
    <label>Column 2 Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Timesheet/main/default/objects/Dashboard_Profile_Config__mdt/fields/Column_3_Fields__c.field-meta.xml
<CustomField>
    <fullName>Column_3_Fields__c</fullName>
    <label>Column 3 Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Timesheet/main/default/objects/Dashboard_Profile_Config__mdt/fields/Show_Null_Fields__c.field-meta.xml
<CustomField>
    <fullName>Show_Null_Fields__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Null Fields</label>
    <type>Checkbox</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Employee__c/fields/Client_Manager__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Client_Manager_email__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager_email__c</fullName>
    <label>Client Manager email</label>
    <type>Email</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/No_of_Vacations_Taken__c.field-meta.xml
<CustomField>
    <fullName>No_of_Vacations_Taken__c</fullName>
    <label>No. of Vacations Taken</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Total_Absence_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Absence_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Absence Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
    <inlineHelpText>Displays the cumulative absence hours from all Approved timesheets. Any Extra Absence Hours entered are also included when newly approved timesheets are processed.</inlineHelpText>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Total_Absence_Hours_Available__c.field-meta.xml
<CustomField>
    <fullName>Total_Absence_Hours_Available__c</fullName>
    <formula>Total_Accrued_Hours__c -  Total_Absence_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Absence Hours Available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
    <inlineHelpText>Shows the employee's remaining absence balance, calculated by subtracting Total Absence Hours from Total Accrued Hours.</inlineHelpText>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Total_Accrued_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Accrued_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Accrued Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
    <inlineHelpText>Shows the sum of accrued hours from all approved timesheets, including manually added Extra Accrued Hours, updated when any timesheet is approved.</inlineHelpText>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Project_Employee__c/Project_Employee__c.object-meta.xml
<CustomObject>
    <label>Project Employee</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Created 1st</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Employees</relationshipLabel>
    <relationshipName>Project_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Timesheet/main/default/objects/Project_Employee__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Project__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet__c/fields/Absence_Hours__c.field-meta.xml
<CustomField>
    <fullName>Absence_Hours__c</fullName>
    <label>Absence Hours</label>
    <summarizedField>Timesheet_Line_Item__c.Duration__c</summarizedField>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Absence</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Absence_Category__c</field>
        <operation>notEqual</operation>
        <value>Holiday</value>
    </summaryFilterItems>
    <summaryForeignKey>Timesheet_Line_Item__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
    <inlineHelpText>Calculates total absence hours from absence entries on timesheets, excluding any logged Holiday hours.</inlineHelpText>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Hours__c</fullName>
    <label>Billable Hours</label>
    <summarizedField>Timesheet_Line_Item__c.Duration__c</summarizedField>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Billable__c</field>
        <operation>equals</operation>
        <value>Yes</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Attendance</value>
    </summaryFilterItems>
    <summaryForeignKey>Timesheet_Line_Item__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Timesheet_Masters</relationshipName>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Non_Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Non_Billable_Hours__c</fullName>
    <label>Non Billable Hours</label>
    <summarizedField>Timesheet_Line_Item__c.Duration__c</summarizedField>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Billable__c</field>
        <operation>equals</operation>
        <value>No</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Timesheet_Line_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Attendance</value>
    </summaryFilterItems>
    <summaryForeignKey>Timesheet_Line_Item__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <formula>Absence_Hours__c  +  Billable_Hours__c  + Non_Billable_Hours__c +  Holiday_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Timesheet/main/default/classes/GetDashboardProfileDetails.cls
/**
 * @description Class to retrieve dashboard profile details including employee and timesheet information
 * @author Ayan
 */
public with sharing class GetDashboardProfileDetails {
    
    /**
     * @description Retrieves employee details and timesheet summary for dashboard display
     * @param userID The ID of the user to fetch profile details for
     * @return Map<String, Object> Contains employee details and timesheet summary
     * @throws AuraHandledException if insufficient permissions or other errors occur
     */
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getEmployeeDetails(Id userID) {
        try {
            // For testing userId is '005fK000000xxC9QAI'
            // userID = Id.valueOf('005fK000000xxC9QAI');
            
            Map<String, Object> resultData = new Map<String, Object>();
            
            // Fetch Employee Details
            Employee__c employeeRecord = getEmployeeRecord(userID);
            populateEmployeeDetails(resultData, employeeRecord);
            
            // Fetch Timesheet Hours Summary
            AggregateResult timesheetSummary = getTimesheetSummary(userID);
            populateTimesheetSummary(resultData, timesheetSummary);
            
            return resultData;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
     * @description Retrieves dashboard profile configuration from Custom Metadata
     * @return Dashboard_Profile_Config__mdt The configuration record
     */
    @AuraEnabled(cacheable=true)
    public static Dashboard_Profile_Config__mdt getProfileConfig() {
        return [
            SELECT Column_1_Fields__c, Column_2_Fields__c, Column_3_Fields__c, Show_Null_Fields__c
            FROM Dashboard_Profile_Config__mdt
            WHERE DeveloperName = 'Default_Value'
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
    
    /**
     * @description Retrieves employee record with related project information
     * @param userID The ID of the user
     * @return Employee__c Employee record with related data
     */
    private static Employee__c getEmployeeRecord(Id userID) {
        return [
            SELECT Id, Name, Client_Manager__r.Name, Client_Manager_email__c,Email__c,Hire_Date__c,Last_Working_Date__c,No_of_Vacations_Taken__c,Phone_Number__c,Total_Accrued_Hours__c,Total_Absence_Hours__c,Total_Absence_Hours_Available__c,
                (SELECT Project_Name__c FROM Project_Employees__r)
            FROM Employee__c
            WHERE User__c = :userID
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
    
    /**
     * @description Retrieves timesheet summary aggregated data
     * @param userID The ID of the user
     * @return AggregateResult Aggregated timesheet data
     */
    private static AggregateResult getTimesheetSummary(Id userID) {
        return [
            SELECT 
                SUM(Billable_Hours__c) TotalBillableHours, 
                SUM(Non_Billable_Hours__c) TotalNonBillableHours, 
                SUM(Absence_Hours__c) TotalAbsenceHours, 
                SUM(Total_Hours__c) TotalHours
            FROM Timesheet__c
            WHERE 
                Employee__c IN (SELECT id FROM Employee__c WHERE User__c = :userID)
                AND
                Start_Date__c = THIS_YEAR
            WITH SECURITY_ENFORCED
        ];
    }
    
    /**
     * @description Populates employee details in the result map
     * @param resultData Map to store the results
     * @param emp Employee record to process
     */
    private static void populateEmployeeDetails(Map<String, Object> resultData, Employee__c emp) {
        // Basic Information
        resultData.put('Name', emp.Name);
        resultData.put('ClientManager', emp.Client_Manager__r?.Name);
        resultData.put('ClientManagerEmail', emp.Client_Manager_email__c);

        // Additional fields from query
        resultData.put('Email', emp.Email__c);
        resultData.put('HireDate', emp.Hire_Date__c);
        resultData.put('LastWorkingDate', emp.Last_Working_Date__c);
        resultData.put('ThisYearVacationsTaken', emp.No_of_Vacations_Taken__c);
        resultData.put('PhoneNumber', emp.Phone_Number__c);

        // Accrued and Absence Hours
        resultData.put('ApprovedAccruedHours', emp.Total_Accrued_Hours__c != null ? emp.Total_Accrued_Hours__c.setScale(2) : null);
        resultData.put('ApprovedAbsenceHours', emp.Total_Absence_Hours__c != null ? emp.Total_Absence_Hours__c.setScale(2) : null);
        resultData.put('ApprovedAbsenceHoursAvailable', emp.Total_Absence_Hours_Available__c != null ? emp.Total_Absence_Hours_Available__c.setScale(2) : null);
        
        // Project information
        List<String> projectNames = new List<String>();
        if (emp.Project_Employees__r != null) {
            for (Project_Employee__c proj : emp.Project_Employees__r) {
                if (proj.Project_Name__c != null) {
                    projectNames.add(proj.Project_Name__c);
                }
            }
        }
        resultData.put('Projects', projectNames.isEmpty() ? 'No Projects Assigned' : String.join(projectNames, ', '));
    }
    
    /**
     * @description Populates timesheet summary in the result map
     * @param resultData Map to store the results
     * @param hours AggregateResult containing timesheet summary
     */
    private static void populateTimesheetSummary(Map<String, Object> resultData, AggregateResult hours) {
        resultData.put('ThisYearBillableHours', (Decimal) hours.get('TotalBillableHours'));
        resultData.put('ThisYearNonBillableHours', (Decimal) hours.get('TotalNonBillableHours'));
        resultData.put('ThisYearAbsenceHours', (Decimal) hours.get('TotalAbsenceHours'));
        resultData.put('ThisYearTotalHours', (Decimal) hours.get('TotalHours'));
    }
}