Timesheet/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Employee__c/fields/Accrual_Divisor__c.field-meta.xml
<CustomField>
    <fullName>Accrual_Divisor__c</fullName>
    <defaultValue>9</defaultValue>
    <label>Accrual Divisor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Accrual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrual_Start_Date__c</fullName>
    <label>Accrual Start Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
                <default>true</default>
                <label>Full Time</label>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Internship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees1</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Timesheet/main/default/objects/Project__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <label>Billable</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Project_Activity__c/Project_Activity__c.object-meta.xml
<CustomObject>
    <label>Project Activity</label>
    <nameField>
        <label>Project Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project_Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Activities</relationshipLabel>
    <relationshipName>Project_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Project_Employee__c/Project_Employee__c.object-meta.xml
<CustomObject>
    <label>Project Employee</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Created 1st</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Employees</relationshipLabel>
    <relationshipName>Project_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Timesheet/main/default/objects/Project_Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select Active Projects</errorMessage>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employees</relationshipLabel>
    <relationshipName>Project_Employees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Timesheet_Masters</relationshipName>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheet_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/Timesheet_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Item</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documentation / Review</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Analysis / Exploration</fullName>
            </value>
            <value>
                <fullName>Development-Admin</fullName>
            </value>
            <value>
                <fullName>Development-Coding</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Social Media Post</fullName>
            </value>
            <value>
                <fullName>Mentoring / Training</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <label>Billable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Time_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Time_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Project_Employee__c.field-meta.xml
<CustomField>
    <fullName>Project_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Employee</label>
    <referenceTo>Project_Employee__c</referenceTo>
    <relationshipLabel>Time Sheet Line Items</relationshipLabel>
    <relationshipName>Time_Sheet_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Time Sheet Line Items</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendance</fullName>
                <default>true</default>
                <label>Attendance</label>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static User createStandardUser(String firstName, String lastName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u = new User();
        u.Email = 'testEmail@' + Datetime.now().format('hh.mm.ss.SSS') + '.com';
        u.ProfileId = p.Id;
        u.Username = 'testUserName' + Datetime.now().format('hh.mm.ss.SSS') + '@testmail.com';
        u.Alias = 'abcd';
        u.CommunityNickname = 'nickName' + Datetime.now().format('hh.mm.ss.SSS');
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ManagerId = UserInfo.getUserId();
        u.LanguageLocaleKey = 'en_US';
        u.FirstName = firstName;
        u.LastName = lastName;
        u.Phone = '9876543210';
        return u;
    }

    public static User createAdminUser(String firstName, String lastName) {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User u = new User();
        u.Email = 'testEmail@' + Datetime.now().format('hh.mm.ss.SSS') + '.com';
        u.ProfileId = p.Id;
        u.Username = 'testUserName' + Datetime.now().format('hh.mm.ss.SSS') + '@testmail.com';
        u.Alias = 'abcd';
        u.CommunityNickname = 'nickName' + Datetime.now().format('hh.mm.ss.SSS');
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ManagerId = UserInfo.getUserId();
        u.LanguageLocaleKey = 'en_US';
        u.FirstName = firstName;
        u.LastName = lastName;
        u.Phone = '9876543210';
        return u;
    }

    public static void assignPermissionSet(User u, String permissionSetName) {
        Id userId = UserInfo.getUserId();
        User adminUser = [SELECT Id FROM User WHERE Id = :userId];
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = :permissionSetName LIMIT 1];
        System.runAs(adminUser) {
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = ps.Id;
            psa.AssigneeId = u.Id;
            insert psa;
        }
    }

    public static Employee__c createEmployee(Id userId) {
        Employee__c employee = new Employee__c();
        employee.Name = 'Test Employee';
        employee.OwnerId = userId;
        employee.First_Name__c = 'Test';
        employee.Last_Name__c = 'Employee';
        employee.User__c = userId;
        employee.Email__c = 'testEmail@' + Datetime.now().format('hh.mm.ss.SSS') + '.com';
        employee.Manager__c = UserInfo.getUserId();
        employee.Employment_Type__c = 'Full Time';
        employee.Accrual_Start_Date__c = System.today().addDays(-30);
        employee.Accrual_Divisor__c = 2;
        return employee;
    }

    public static Timesheet__c createTimesheet(Id employeeId) {
        Timesheet__c timesheet = new Timesheet__c();
        timesheet.Start_Date__c = System.today();
        timesheet.End_Date__c = System.today() + 6;
        timesheet.Name = 'Timesheet for ' + timesheet.Start_Date__c + ' to ' + timesheet.End_Date__c;
        timesheet.Employee__c = employeeId;
        timesheet.Status__c = 'New';
        return timesheet;
    }

    public static Project__c createProject(String projectName, String isBillable) {
        Project__c project = new Project__c();
        project.Name = projectName;
        project.Start_Date__c = System.today();
        project.End_Date__c = System.today() + 365;
        project.Active__c = true;
        project.Billable__c = isBillable;
        return project;
    }

    public static Project_Activity__c createProjectActivity(Id projectId, String activityName) {
        Project_Activity__c act = new Project_Activity__c();
        act.Name = activityName;
        act.Project__c = projectId;
        return act;
    }

    public static Project_Employee__c createProjectEmployee(Id projectId, Id employeeId) {
        Project_Employee__c projectEmployee = new Project_Employee__c();
        projectEmployee.Project__c = projectId;
        projectEmployee.Employee__c = employeeId;
        return projectEmployee;
    }

    public static Timesheet_Line_Item__c createTimesheetLineItem(Id timesheetId, Id projectId, Id activityId) {
        Timesheet_Line_Item__c tli = new Timesheet_Line_Item__c();
        tli.Type__c = 'Attendance';
        tli.Timesheet__c = timesheetId;
        tli.Date__c = System.today();
        tli.Project__c = projectId;
        tli.Activity__c = activityId;
        tli.Duration__c = 5;
        tli.Description__c = 'Test Description';
        return tli;
    }
}