Timesheet/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project_Employee__c/Project_Employee__c.object-meta.xml
<CustomObject>
    <label>Project Employee</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Project Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Project_Employee__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Created 1st</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Employees</relationshipLabel>
    <relationshipName>Project_Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Timesheet/main/default/objects/Project_Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select Active Projects</errorMessage>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Employees</relationshipLabel>
    <relationshipName>Project_Employees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/classes/ProjectController.cls
public with sharing class ProjectController {
    
    @AuraEnabled
    public static List<Project_Employee__c> getProjects(String empId){
        try {
            if(Project_Employee__c.SObjectType.getDescribe().isAccessible() 
                && Schema.SObjectType.Project_Employee__c.fields.Id.isAccessible() 
                && Schema.SObjectType.Project_Employee__c.fields.Project__c.isAccessible() 
                && Schema.SObjectType.Project_Employee__c.fields.Employee__c.isAccessible()){
                    return [select Id,
                                            Name, 
                                            Project__c, 
                                            Project__r.Name, 
                                            Employee__c 
                                            from Project_Employee__c 
                                            Where Employee__c =: empId
                                            with SECURITY_ENFORCED];
            } else{
                throw new AuraHandledException('You do not have access, please contact System Admin');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}