Timesheet/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet_Line_Item__c/Timesheet_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line Item</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Absence_Category__c.field-meta.xml
<CustomField>
    <fullName>Absence_Category__c</fullName>
    <label>Absence Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Duty</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Permission</fullName>
            </value>
            <value>
                <fullName>PTO-Planned</fullName>
            </value>
            <value>
                <fullName>PTO-Un Planned</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documentation / Review</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Analysis / Exploration</fullName>
            </value>
            <value>
                <fullName>Development-Admin</fullName>
            </value>
            <value>
                <fullName>Development-Coding</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Social Media Post</fullName>
            </value>
            <value>
                <fullName>Mentoring / Training</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Time_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Time Sheet Line Items</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Timesheet/main/default/objects/Timesheet_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attendance</fullName>
                <default>true</default>
                <label>Attendance</label>
            </value>
            <value>
                <fullName>Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Timesheet/main/default/classes/TimesheetLineItemLwcController.cls
public with sharing class TimesheetLineItemLwcController {
    private static string errorMessage = 'You do not have access, please contact System Admin';
    
    @AuraEnabled(cacheable=true)
    public static List<Timesheet_Line_Item__c> getTimesheetLineItems(Id timesheetId){
        try{
            return [SELECT Id, Type__c, Timesheet__c, Date__c, Project__c, Activity__c, Absence_Category__c, Description__c, Duration__c FROM Timesheet_Line_Item__c WHERE Timesheet__c=:timesheetId WITH SECURITY_ENFORCED ORDER BY Date__c ASC];
        } catch (Exception e){
            AuraHandledException ae = new AuraHandledException(errorMessage);
            ae.setMessage(errorMessage);
            throw ae;
        }
    }
    
    @AuraEnabled
    public static void updateTimesheetLineItems(List<Timesheet_Line_Item__c> timesheetLineItems, String[] idsToDelete){
        if(idsToDelete != null && idsToDelete.size() > 0){
            deleteTimesheetLineItems(idsToDelete);
        }
        if(timesheetLineItems != null && timesheetLineItems.size() >0){
            upsertTimesheetRecords(timesheetLineItems);
        }
    }

    private static void upsertTimesheetRecords(List<Timesheet_Line_Item__c> timesheetLineItems){
        try{
            SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPSERTABLE, timesheetLineItems);
            upsert securityDecision.getRecords();
        } catch (Exception e){
            AuraHandledException ae = new AuraHandledException(errorMessage);
            ae.setMessage(errorMessage);
            throw ae;
        }
    }

    private static void deleteTimesheetLineItems(String[] timesheetIds){
        try{
            List<Timesheet_Line_Item__c> timesheetLineItems = [SELECT Id from Timesheet_Line_Item__c WHERE Id IN : timesheetIds WITH SECURITY_ENFORCED];
            if(Timesheet_Line_Item__c.SObjectType.getDescribe().isDeletable()){
                delete timesheetLineItems;
            } else {
                throw new AuraHandledException(errorMessage);
            }
        } catch (Exception e){
            AuraHandledException ae = new AuraHandledException(errorMessage);
            ae.setMessage(errorMessage);
            throw ae;
        }
    }
}